### ISSUE TITLE
Bug: Arrow heads point in the wrong direction

### ISSUE THREAD

**Issue by niermann999** [acts-project/actsvg#59]
After the recent version update of actsvg in detray, I noticed that the arrow heads all point in the same direction, both on axes as well as on portal links. E.g. see the y axis in the following svg:
![toy_detector_disc_material_xy](https://github.com/acts-project/actsvg/assets/53186085/d6ac0ded-fb84-4bb3-9db6-ffdce983b9b5)

**Comment by asalzburger** [comment]
Yeah, the problem was that the group transform was not written out anymore.
