### ISSUE TITLE
Colors have disappeared from material map gradient stops

### ISSUE THREAD

**Issue by niermann999** [acts-project/actsvg#70]
Is it also possible to set a label for the gradient scale?
This is from the unittests:
![test_meta_surface_material_r_phi](https://github.com/acts-project/actsvg/assets/53186085/8579d1c0-0a17-471e-9483-2bcb4dde8481)

**Comment by asalzburger** [comment]
The color issue should be fixed, that's with current head:

<img width="847" alt="Screenshot 2024-06-18 at 06 41 44" src="https://github.com/acts-project/actsvg/assets/26623879/1312a190-f6b8-4a18-aeb4-e85d58e5874f">

**Comment by asalzburger** [comment]
#72 should add the labelling.
